### ISSUE TITLE
NPE when enableassertions option is enabled

### ISSUE THREAD

**Issue by pdulth** [pdulth/dmi2#110]
When JVM option 'enableassertions' is enabled, a NPE occurs:

Caused by: java.lang.NullPointerException

            at org.eclipse.emf.diffmerge.impl.helpers.UnidirectionalComparisonCopier.getCompletedMatches(UnidirectionalComparisonCopier.java:256)

            at org.eclipse.emf.diffmerge.impl.helpers.UnidirectionalComparisonCopier.completeMatch(UnidirectionalComparisonCopier.java:103)

`🆔 ECLIPSE-480191` `👷 jean.barata` `📅 2015-10-20` `🔎 0.5.0`

**Comment by pdulth** [comment]
**ci-bot** commented on 2015-10-20
> Gerrit change https://git.eclipse.org/r/58500 was merged to [master].
 > Commit: http://git.eclipse.org/c/diffmerge/org.eclipse.emf.diffmerge.core.git/commit/?id=77ee90a029b994c722e07423e839a590c8ec41d3

**olivier.constant** commented on 2015-10-20
> An evolution of the way this class is initialized led to the need to move the assertion after the next line of code.
 > Well, I would call that a quick fix. :)

**olivier.constant** commented on 2017-01-10
> Closing.
