### ISSUE TITLE
[log4j] getMessageBody doesn't support tuples

### ISSUE THREAD

**Issue by pdulth** [pdulth/dmi2#161]
When using log4j with coevolution rules, i get the following exceptions:

java.lang.ClassCastException: org.eclipse.emf.diffmerge.bridge.util.structures.Tuple2 cannot be cast to org.eclipse.emf.ecore.EObject
	at org.eclipse.emf.diffmerge.bridge.mapping.util.QueryLoggingMessage.getMessageBody(QueryLoggingMessage.java:87)
	at org.eclipse.emf.diffmerge.bridge.util.AbstractLoggingMessage.toString(AbstractLoggingMessage.java:60)
	at org.eclipse.emf.diffmerge.bridge.log4j.BridgeLogger.info(BridgeLogger.java:111)
	at org.eclipse.emf.diffmerge.bridge.log4j.BridgeLogger.handleInfoEvent(BridgeLogger.java:151)
	at org.eclipse.emf.diffmerge.bridge.log4j.BridgeLogger.handleLoggingEvent(BridgeLogger.java:87)
[...]

It seems that getMessageBody doesn't support tuples.

`🆔 ECLIPSE-513566` `👷 olivier.gilles` `📅 2017-03-13` `🔎 0.7.0`

**Comment by pdulth** [comment]
**ci-bot** commented on 2017-03-14
> Gerrit change https://git.eclipse.org/r/93034 was merged to [master].
 > Commit: http://git.eclipse.org/c/diffmerge/org.eclipse.emf.diffmerge.coevolution.git/commit/?id=896005747a3c3148b34e48d535c1d11d7a674446

**olivier.constant** commented on 2017-03-15
> Marking as fixed since I got your positive feedback.

**olivier.constant** commented on 2017-12-19
> Integrated in v0.8.0, closing.
