### ISSUE TITLE
[Coevolution] traces crash when using Sets as cause

### ISSUE THREAD

**Issue by pdulth** [pdulth/dmi2#180]
When using Sets as cause, in some case, the log system crash (cf. stack trace below). When i comment the responsible code (which just print some logs) the transition works properly. 

code :
    for (Object source : getCause().getSourceElements()) {
      String sourceName = getObjectLabel(source);
    /*  String sourceType = ((EObject) source).eClass().getName();
     * builder.append("("); //$NON-NLS-1$
     * builder.append(sourceType).append(" \""); //$NON-NLS-1$*/
      builder.append(sourceName).append("\""); //$NON-NLS-1$
      builder.append("[").append(function.getSymbol(source)).append("])");//$NON-NLS-1$ //$NON-NLS-2$ 
    }

stacktrace :
!MESSAGE An internal error occurred during: "uml export".
!STACK 0
java.lang.ClassCastException: java.util.HashSet cannot be cast to org.eclipse.emf.ecore.EObject
	at org.eclipse.emf.diffmerge.bridge.mapping.util.TraceLoggingMessage.getMessageBody(TraceLoggingMessage.java:60)
	at org.eclipse.emf.diffmerge.bridge.util.AbstractLoggingMessage.toString(AbstractLoggingMessage.java:58)
	at org.eclipse.emf.diffmerge.bridge.log4j.BridgeLogger.info(BridgeLogger.java:247)
	at org.eclipse.emf.diffmerge.bridge.log4j.BridgeLogger.handleInfoEvent(BridgeLogger.java:151)
	at org.eclipse.emf.diffmerge.bridge.log4j.BridgeLogger.handleLoggingEvent(BridgeLogger.java:170)
	at org.eclipse.emf.diffmerge.bridge.log4j.BridgeLoggingAppender.notifyListeners(BridgeLoggingAppender.java:89)
	at org.eclipse.emf.diffmerge.bridge.log4j.BridgeLoggingAppender.append(BridgeLoggingAppender.java:64)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.eclipse.emf.diffmerge.bridge.log4j.BridgeLoggingAppender.doAppend(BridgeLoggingAppender.java:80)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.info(Category.java:666)
	at org.eclipse.emf.diffmerge.bridge.impl.AbstractBridgeExecution.putInTraceAtomic(AbstractBridgeExecution.java:116)
	at org.eclipse.emf.diffmerge.bridge.impl.AbstractBridgeExecution.putInTrace(AbstractBridgeExecution.java:101)
	at org.eclipse.emf.diffmerge.bridge.mapping.impl.MappingExecution.putInTrace(MappingExecution.java:253)
	at org.eclipse.emf.diffmerge.bridge.mapping.operations.MappingBridgeOperation.handleRuleForTargetDefinition(MappingBridgeOperation.java:284)
	at org.eclipse.emf.diffmerge.bridge.mapping.operations.MappingBridgeOperation.handleRuleForTargetDefinitions(MappingBridgeOperation.java:259)
	at org.eclipse.emf.diffmerge.bridge.mapping.operations.MappingBridgeOperation.handleTargetDefinitions(MappingBridgeOperation.java:239)
	at org.eclipse.emf.diffmerge.bridge.uml.mapping.UMLMappingBridgeOperation.handleBridge(UMLMappingBridgeOperation.java:93)
	at org.eclipse.emf.diffmerge.bridge.mapping.operations.MappingBridgeOperation.run(MappingBridgeOperation.java:295)
	at org.eclipse.emf.diffmerge.impl.helpers.AbstractExpensiveOperation.run(AbstractExpensiveOperation.java:69)
	at org.eclipse.emf.diffmerge.bridge.mapping.impl.MappingBridge.executeOn(MappingBridge.java:93)
	at org.eclipse.emf.diffmerge.bridge.mapping.impl.MappingBridge.executeOn(MappingBridge.java:1)
	at org.eclipse.emf.diffmerge.bridge.operations.IncrementalWrappingBridgeOperation.run(IncrementalWrappingBridgeOperation.java:118)
	at org.eclipse.emf.diffmerge.impl.helpers.AbstractExpensiveOperation.run(AbstractExpensiveOperation.java:69)
	at org.eclipse.emf.diffmerge.bridge.impl.emf.AbstractWrappingIncrementalBridge.executeOn(AbstractWrappingIncrementalBridge.java:91)
	at org.eclipse.emf.diffmerge.bridge.interactive.BridgeJob$2.run(BridgeJob.java:274)
	at org.eclipse.emf.diffmerge.ui.util.MiscUtil.executeAndForget(MiscUtil.java:227)
	at org.eclipse.emf.diffmerge.ui.util.MiscUtil.execute(MiscUtil.java:201)
	at org.eclipse.emf.diffmerge.bridge.interactive.BridgeJob.run(BridgeJob.java:279)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

`🆔 ECLIPSE-515911` `👷 olivier.gilles` `📅 2017-04-27` `🔎 0.7.0`

**Comment by pdulth** [comment]
**olivier.gilles** commented on 2017-04-28
> (In reply to ci-bot from comment #1)
 > > New Gerrit change created: https://git.eclipse.org/r/95994
 > 
 > It looks fixed, but I have to proceed to more extensive testing to answer. Since I am in vacation tonight, the answer will in the second half of may.

**ci-bot** commented on 2017-05-02
> Gerrit change https://git.eclipse.org/r/95994 was merged to [master].
 > Commit: http://git.eclipse.org/c/diffmerge/org.eclipse.emf.diffmerge.coevolution.git/commit/?id=8ecb6518e0453c2ff698c1a8031802b8ab571a15

**olivier.constant** commented on 2017-05-02
> OK; marking as solved, please re-open if there are still issues.

**olivier.constant** commented on 2017-12-19
> Integrated in v0.9.0, closing.
