### ISSUE TITLE
NotSerializableException while saving EComparison

### ISSUE THREAD

**Issue by pdulth** [pdulth/dmi2#19]
Hi,

I am trying to save an EComparison object via the EMF Resource mechanism, but this throws a "NotSerializableException" during Resource.save:

...
Caused by: java.io.NotSerializableException: org.eclipse.emf.diffmerge.diffdata.impl.EMatchImpl
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at org.eclipse.emf.ecore.impl.EFactoryImpl.convertToString(EFactoryImpl.java:673)
	... 74 more

Analysis: The 'value' attribute of an EReferenceValuePresence holds an EMatch, but EMatch is not Serializable.

`🆔 ECLIPSE-416493` `👷 felix.dorner` `📅 2013-09-04`

**Comment by pdulth** [comment]
**olivier.constant** commented on 2013-09-05
> Confirmed: this is due to EValuePresence having attribute 'value' typed with EJavaObject. It corresponds to the value of an attribute (Object) in subclass EAttributeValuePresence and the value of a reference (EObject) in subclass EReferenceValuePresence. We have to change this to support serializing.

**ci-bot** commented on 2018-07-18
> Gerrit change https://git.eclipse.org/r/123265 was merged to [master].
 > Commit: http://git.eclipse.org/c/diffmerge/org.eclipse.emf.diffmerge.core.git/commit/?id=59cce0019f3b10246992ac5f9dd2db56a92cf1b7

**felix.dorner** commented on 2018-08-09
> Little strokes fell big oaks. Nice!

**olivier.constant** commented on 2018-08-09
> Nice saying that carries more positive connotation than "Better late than never". ;-)

**jabier.martinez** commented on 2018-08-09
> Nice! This should have been triggered by some new amazing feature! We will stay tuned.

**olivier.constant** commented on 2018-09-06
> Actually, it turned out to be very useful for several completely different needs. We are prototyping stuff but it's too early to be released in open source. We may have the opportunity to do it later, though, with a bit of luck.
