### ISSUE TITLE
NPE when using structure with empty origins

### ISSUE THREAD

**Issue by pdulth** [pdulth/dmi2#225]
When creating an IImpact.Invertible with an empty collection as origins, the following NPE happens:

java.lang.NullPointerException
	at org.eclipse.emf.diffmerge.structures.endo.CachingEndorelation$1.update(CachingEndorelation.java:210)
	at org.eclipse.emf.diffmerge.structures.endo.BreadthFirstIterator.<init>(BreadthFirstIterator.java:57)
	at org.eclipse.emf.diffmerge.structures.endo.CachingEndorelation$1.<init>(CachingEndorelation.java:202)
	at org.eclipse.emf.diffmerge.structures.endo.CachingEndorelation.newExplorationIterator(CachingEndorelation.java:202)
	at org.eclipse.emf.diffmerge.structures.endo.CachingEndorelation.<init>(CachingEndorelation.java:70)
	at org.eclipse.emf.diffmerge.structures.endo.qualified.CachingQEndorelation.<init>(CachingQEndorelation.java:59)
	at org.eclipse.emf.diffmerge.structures.endo.qualified.CachingQEndorelation.<init>(CachingQEndorelation.java:45)
	at org.eclipse.emf.diffmerge.structures.endo.qualified.CachingInvertibleQEndorelation.<init>(CachingInvertibleQEndorelation.java:39)
	at org.eclipse.emf.diffmerge.structures.impacts.InvertibleImpact.<init>(InvertibleImpact.java:51)
	at org.eclipse.emf.diffmerge.structures.impacts.InvertibleImpact.<init>(InvertibleImpact.java:40)
	at org.eclipse.emf.diffmerge.structures.impacts.Impacts.createInvertible(Impacts.java:67)

DiffMerge version: 0.9.0.201710040906

`🆔 ECLIPSE-525578` `👷 florent.latombe` `📅 2017-10-04`

**Comment by pdulth** [comment]
**olivier.constant** commented on 2017-10-05
> While the instance variable involved is documented as always non-null, the NPE comes from the fact that the receiver object has not been initialized yet when the method involved is executed in the context of an impact without origin elements. Fixed by simply checking for a null value.

**ci-bot** commented on 2017-10-05
> Gerrit change https://git.eclipse.org/r/106267 was merged to [master].
 > Commit: http://git.eclipse.org/c/diffmerge/org.eclipse.emf.diffmerge.core.git/commit/?id=c023e2821ee05289e42a8fabe59a59bb8b9f2a57

**olivier.constant** commented on 2017-10-05
> AFAICT, it is fixed.

**olivier.constant** commented on 2017-12-19
> Integrated in 0.9.0, closing.
