### ISSUE TITLE
NPE on cancel when no differences

### ISSUE THREAD

**Issue by pdulth** [pdulth/dmi2#24]
java.lang.NullPointerException
	at org.eclipse.emf.diffmerge.ui.actions.EMFDiffMergeEditorInput.getEditingDomain(EMFDiffMergeEditorInput.java:261)
	at org.eclipse.emf.diffmerge.ui.actions.EMFDiffMergeEditorInput.disposeResources(EMFDiffMergeEditorInput.java:185)
	at org.eclipse.emf.diffmerge.ui.actions.EMFDiffMergeEditorInput$4.run(EMFDiffMergeEditorInput.java:293)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.emf.diffmerge.ui.actions.EMFDiffMergeEditorInput.handleDispose(EMFDiffMergeEditorInput.java:307)
	at org.eclipse.emf.diffmerge.ui.actions.EMFDiffMergeEditorInput$1.widgetDisposed(EMFDiffMergeEditorInput.java:139)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)

`🆔 ECLIPSE-417596` `👷 mathieu.velten` `📅 2013-09-19`

**Comment by pdulth** [comment]
**olivier.constant** commented on 2013-10-15
> Comparison method of editor input was assumed to be non-null, which is true unless the editor input has been disposed when resources are being disposed. Due to concurrency and asynchronous computations, this situation could happen.
 > 
 > Commit: a236f0c2d84b736513ddcc6956721a8451b17853

**olivier.constant** commented on 2014-08-19
> Closing.
