### ISSUE TITLE
The "Apply Pattern" window cannot finish

### ISSUE THREAD

**Issue by pdulth** [pdulth/dmi2#248]
The bug is reproducible with Capella (branch master). Here are steps to reproduce with Capella:
1. Create a new SDFB diagram
2. Add some Functions into it
3. Selected added Functions and create a Pattern from them
4. Add a new SDFB
5. Apply the created pattern in this diagram
=> The "Apply Pattern" window cannot finish and the layout of the pattern instance is not copied.

Here is the stack trace:
java.lang.NoSuchMethodError: org.eclipse.sirius.viewpoint.Style.refresh()V
	at org.eclipse.emf.diffmerge.patterns.diagrams.sirius.util.LayoutUtil.applyEdgeStyle(LayoutUtil.java:123)
	at org.eclipse.emf.diffmerge.patterns.diagrams.sirius.operations.SiriusLayoutReuseOperation$InnerLayoutReuseOperation.update(SiriusLayoutReuseOperation.java:426)
	at org.eclipse.emf.diffmerge.patterns.diagrams.sirius.operations.SiriusLayoutReuseOperation.update(SiriusLayoutReuseOperation.java:119)
	at org.eclipse.emf.diffmerge.patterns.diagrams.operations.AbstractFilteredGraphicalUpdateOperation.checkUpdate(AbstractFilteredGraphicalUpdateOperation.java:93)
	at org.eclipse.emf.diffmerge.patterns.diagrams.sirius.operations.SiriusLayoutReuseOperation.run(SiriusLayoutReuseOperation.java:172)
	at org.eclipse.emf.diffmerge.patterns.diagrams.sirius.operations.SiriusFilteredGraphicalUpdateOperation.run(SiriusFilteredGraphicalUpdateOperation.java:1)
	at org.eclipse.emf.diffmerge.patterns.core.operations.AbstractModelOperation.run(AbstractModelOperation.java:177)
	at org.eclipse.emf.diffmerge.patterns.core.operations.CompoundModelOperation.call(CompoundModelOperation.java:93)
	at org.eclipse.emf.diffmerge.patterns.core.operations.CompoundModelOperation.run(CompoundModelOperation.java:80)
	at org.eclipse.emf.diffmerge.patterns.core.operations.CompoundModelOperation.run(CompoundModelOperation.java:1)
	at org.eclipse.emf.diffmerge.patterns.core.operations.AbstractModelOperation.run(AbstractModelOperation.java:177)
	at org.eclipse.emf.diffmerge.patterns.diagrams.sirius.extensions.AbstractSiriusModelEnvironment$OperationWithResultCommand.doExecute(AbstractSiriusModelEnvironment.java:202)
	at org.eclipse.emf.edit.command.ChangeCommand.execute(ChangeCommand.java:130)
	at org.eclipse.emf.workspace.EMFCommandOperation.doExecute(EMFCommandOperation.java:119)
	at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:488)

`🆔 ECLIPSE-537145` `👷 minh.tu.ton.that` `📅 2018-07-18` `🔎 0.10.0`

**Comment by pdulth** [comment]
**ci-bot** commented on 2018-08-29
> Gerrit change https://git.eclipse.org/r/126247 was merged to [master].
 > Commit: http://git.eclipse.org/c/diffmerge/org.eclipse.emf.diffmerge.patterns.git/commit/?id=5da389da8d4fb0eaef74304fca8732205a0b666e

**olivier.constant** commented on 2018-08-29
> Thanks Tu!
