### ISSUE TITLE
modify the unload() of FragmentedmodelScope

### ISSUE THREAD

**Issue by pdulth** [pdulth/dmi2#44]
Hi,

i got an error in the FragmentedScope.unload() while using custom load() method.

I override the load to load the resource via an inputstream, but when the unload() occurs, the _resourceSet.getResources().removeAll(_loadedResources); line causes problems.
see stack [1]

I can avoid this by modifying the unload() this way :
	public List<Resource> unload() {
		for (Resource loadedResource: _loadedResources) {
			for (Adapter adapter: new ArrayList<Adapter>(loadedResource.eAdapters())) {
				if (adapter instanceof ECrossReferenceAdapter)
					loadedResource.eAdapters().remove(adapter);
			}
		}
		for (Resource loadedResource: _loadedResources) {
			if (loadedResource.isLoaded()) {
				loadedResource.unload();
				_resourceSet.getResources().remove(loadedResource); // remove the unloaded resource here does not cause problems.
			}
		}
		//_resourceSet.getResources().removeAll(_loadedResources); // this is causing problems, since the resource is loaded from stream ?
		List<Resource> result=new ArrayList<Resource>(_loadedResources);
		_loadedResources.clear();
		if (!result.isEmpty())
			_state=ScopeState.UNLOADED;
		return result;
	}

I this suitable to use it as patch ?

Regards,

[1]:
!ENTRY org.eclipse.emf.common 2 0 2014-03-28 11:57:02.809
!MESSAGE An exception was ignored during command execution
!STACK 0
org.eclipse.emf.common.util.WrappedException: An exception was ignored during command execution
	at org.eclipse.emf.common.command.BasicCommandStack.handleError(BasicCommandStack.java:281)
	at org.eclipse.emf.common.command.BasicCommandStack.execute(BasicCommandStack.java:112)
	at org.eclipse.emf.diffmerge.ui.util.MiscUtil.executeAndForget(MiscUtil.java:145)
	at org.eclipse.emf.diffmerge.ui.setup.EMFDiffMergeEditorInput.disposeResources(EMFDiffMergeEditorInput.java:224)
	at org.eclipse.emf.diffmerge.ui.setup.EMFDiffMergeEditorInput$6.run(EMFDiffMergeEditorInput.java:401)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.emf.diffmerge.ui.setup.EMFDiffMergeEditorInput.handleDispose(EMFDiffMergeEditorInput.java:415)
	at org.eclipse.emf.diffmerge.ui.setup.EMFDiffMergeEditorInput.prepareInput(EMFDiffMergeEditorInput.java:600)
	at org.eclipse.compare.CompareEditorInput.run(CompareEditorInput.java:484)
	at org.eclipse.emf.diffmerge.ui.setup.EMFDiffMergeEditorInput.run(EMFDiffMergeEditorInput.java:640)
	at com.cofluent.studio.team.viewer.CoFluentModelComparisonViewer.setInput(CoFluentModelComparisonViewer.java:57)
	at org.eclipse.compare.CompareViewerSwitchingPane.setInput(CompareViewerSwitchingPane.java:277)
	at org.eclipse.compare.internal.CompareContentViewerSwitchingPane.setInput(CompareContentViewerSwitchingPane.java:158)
	at org.eclipse.compare.CompareEditorInput.internalSetContentPaneInput(CompareEditorInput.java:845)
	at org.eclipse.compare.CompareEditorInput.access$8(CompareEditorInput.java:843)
	at org.eclipse.compare.CompareEditorInput$11.run(CompareEditorInput.java:779)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.compare.CompareEditorInput.feed1(CompareEditorInput.java:773)
	at org.eclipse.compare.CompareEditorInput.feedInput(CompareEditorInput.java:751)
	at org.eclipse.compare.CompareEditorInput.createContents(CompareEditorInput.java:555)
	at org.eclipse.compare.internal.CompareEditor.createCompareControl(CompareEditor.java:462)
	at org.eclipse.compare.internal.CompareEditor.access$6(CompareEditor.java:422)
	at org.eclipse.compare.internal.CompareEditor$3.run(CompareEditor.java:378)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:164)
	at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:158)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4144)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at Application.start(Application.java:74)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Caused by: java.lang.ClassCastException: [I cannot be cast to java.util.List
	at org.eclipse.gmf.runtime.emf.core.internal.resources.PathmapManager.notifyChanged(PathmapManager.java:598)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.emf.common.notify.impl.NotificationChainImpl.dispatch(NotificationChainImpl.java:98)
	at org.eclipse.emf.common.notify.impl.NotificationChainImpl.dispatch(NotificationChainImpl.java:86)
	at org.eclipse.emf.common.notify.impl.NotifyingListImpl.removeAll(NotifyingListImpl.java:954)
	at mycustomscope.unload(mycustomscope.java:51)
	at org.eclipse.emf.diffmerge.ui.setup.EMFDiffMergeEditorInput$3.run(EMFDiffMergeEditorInput.java:240)
	at org.eclipse.emf.diffmerge.ui.util.MiscUtil$ForgettingCommand.execute(MiscUtil.java:78)
	at org.eclipse.emf.common.command.BasicCommandStack.execute(BasicCommandStack.java:78)
	... 49 more

`🆔 ECLIPSE-431489` `👷 stephane.bouchet` `📅 2014-03-28`

**Comment by pdulth** [comment]
**olivier.constant** commented on 2014-03-28
> OK, weird that a "for (...) remove" is OK while a "removeAll" is not. I'm wondering whether this is a limitation/bug in GMF Runtime. Anyway, as the functional behavior w.r.t. EMF Diff/Merge is preserved I'm OK in making the change if that improves the integrability with GMF. In addition, there should be no performance issue here since there are usually not thousands of resources in a resource set.
 > 
 > Only, the functional behavior is not exactly preserved since, with this patch, non-loaded resources are not removed from the resource set. Is that on purpose? If you move the "remove" instruction out of the "if" clause, is the patch still effective?

**stephane.bouchet** commented on 2014-03-28
> (In reply to olivier.constant from comment #1)
 > 
 > > Only, the functional behavior is not exactly preserved since, with this
 > > patch, non-loaded resources are not removed from the resource set. Is that
 > > on purpose? If you move the "remove" instruction out of the "if" clause, is
 > > the patch still effective?
 > 
 > Yes it is functional this way.
 > debugging this causes my some headhaches since the removeall sent a notification that is not correct Oo...

**olivier.constant** commented on 2014-03-28
> (In reply to stephane.bouchet from comment #2)
 > > Yes it is functional this way.
 > > debugging this causes my some headhaches since the removeall sent a
 > > notification that is not correct Oo...
 > 
 > Well, I would assume that the notification is correct but unexpected...
 > Anyway, since we are confident that we have a fix which has no other particular impact, let's integrate it.

**olivier.constant** commented on 2014-03-28
> Fixed in commit 87805dfc3c05ce31214e286c5141160dd14c00db.
 > Thanks for your contribution Stéphane. :-)

**olivier.constant** commented on 2014-08-19
> Closing.
